# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\history.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_history(object):
    def setupUi(self, history):
        history.setObjectName("history")
        history.resize(1302, 971)
        self.tabWidget = QtWidgets.QTabWidget(history)
        self.tabWidget.setGeometry(QtCore.QRect(20, 40, 1201, 881))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_all = QtWidgets.QWidget()
        self.tab_all.setObjectName("tab_all")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_all)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1191, 841))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_all, "")
        self.tab_week = QtWidgets.QWidget()
        self.tab_week.setObjectName("tab_week")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_week)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 1191, 841))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget_2, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_week, "")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_search)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1191, 841))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.gridLayoutWidget_3)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget_3, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_search, "")

        self.retranslateUi(history)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(history)

    def retranslateUi(self, history):
        _translate = QtCore.QCoreApplication.translate
        history.setWindowTitle(_translate("history", "Form"))
        self.pushButton.setText(_translate("history", "update"))
        self.pushButton_2.setText(_translate("history", "delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_all), _translate("history", "ALL"))
        self.pushButton_3.setText(_translate("history", "update"))
        self.pushButton_4.setText(_translate("history", "delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_week), _translate("history", "Week"))
        self.pushButton_5.setText(_translate("history", "update"))
        self.pushButton_6.setText(_translate("history", "delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), _translate("history", "Search"))

